### ISSUE TITLE
Newer picolibc revisions failing meson setup

### ISSUE THREAD

**Issue by pmiettinen** [keith-packard/pico-hello#1]
Could the example be updated for newer picolibc versions? I think there has been some changes in bringing in the picolibc as meson subproject?

For example with picolibc-1.8.5 the meson setup is currently giving error:

```
ERROR: Requested variable "lib_crt" not found.
```

Thanks for the interesting library!

**Comment by keith-packard** [comment]
Thanks! To make this work, I just needed to switch from using the picocrt library to the picocrt object files directly. I also added a bunch of other cleanups, but the main fix was in meson.build.

 I'll add testing this to the picolibc release process to avoid this in future releases.
